DROP DATABASE MovieCatalogue;

CREATE DATABASE IF NOT EXISTS MovieCatalogue;

USE MovieCatalogue;

CREATE TABLE IF NOT EXISTS Genre(
	GenreID INT PRIMARY KEY AUTO_INCREMENT,
	GenreName VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Director(
	DirectorID INT PRIMARY KEY AUTO_INCREMENT,
	FirstName VARCHAR(30) NOT NULL,
    LastName VARCHAR(30) NOT NULL,
    BirthDate DATE
);

CREATE TABLE IF NOT EXISTS Rating(
	RatingID INT PRIMARY KEY AUTO_INCREMENT,
    RatingName VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS Actor(
	ActorID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(30) NOT NULL,
    LastName VARCHAR(30) NOT NULL,
    BirthDate DATE
);

CREATE TABLE IF NOT EXISTS Movie(
	MovieID INT PRIMARY KEY AUTO_INCREMENT,
    GenreID INT NOT NULL,
    DirectorID INT,
    RatingID INT,
    Title VARCHAR(128) NOT NULL,
    ReleaseDate DATE,
    CONSTRAINT fk_Movie_Genre FOREIGN KEY(GenreID)
		REFERENCES Genre(GenreID),
	CONSTRAINT fk_Movie_Director FOREIGN KEY(DirectorID)
		REFERENCES Director(DirectorID),
	CONSTRAINT fk_Movie_Rating FOREIGN KEY(RatingID)
		REFERENCES Rating(RatingID)
);

CREATE TABLE IF NOT EXISTS CastMembers(
	CastMemberID INT PRIMARY KEY AUTO_INCREMENT,
	ActorID INT NOT NULL,
    MovieID INT NOT NULL,
    `Role` VARCHAR(50) NOT NULL,
    CONSTRAINT fk_CastMembers_Actor FOREIGN KEY (ActorID)
		REFERENCES Actor(ActorID),
	CONSTRAINT fk_CastMembers_Movie FOREIGN KEY(MovieID)
		REFERENCES Movie(MovieID)
);
